### ISSUE TITLE
syntax error when running

### ISSUE THREAD

**Issue by ghost** [dwkns/ruby-iTerm2#3]
I get this following error: `166:172: syntax error: Expected end of line but found class name. (-2741)`
Any idea what's going on?

**Comment by dwkns** [comment]
Hmmmm. That's an odd one and I can't reproduce it.

 That error can be caused by a few things. 

1) iTerm not being found on your machine. Ensure that you have iTerm2 ( > v2.9) installed and it is called iTerm.app in your /Applications folder. The latest download should work ok.

2) It's more commonly caused by an error in AppleScript code when quotes or line breaks are not used properly.  Have you edited` ruby-iTerm2.sh` ?

What version of OS X are you using?
What version of iTerm2 are you using?
How did you install iTerm2, directly by downloading or by brew cask?
